# copy of docker running
sudo: required # because we use dockefile
services:
    - docker

# build our image using Dockerfile.dev
before_install:
    -  docker build -t ferminhg/docker-react -f Dockerfile.dev .

# tell travis how to run our test suite
script:
    - docker run ferminhg/docker-react npm run test -- --watchAll=false

# tell travis how to deploy AWS

deploy:
    provider: elasticbeanstalk
    edge: true
    region: "eu-west-3"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-eu-west-3-786016240807"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: "$AWS_SECRET_KEY"
